version: '3'

networks:
  brewing:
    external:
      name: brewing-ingress_brewing

services:
  influxdb:
    container_name: auto-home-influx
    hostname: auto-home-influx
    image: influxdb:1.8
    restart: always
    networks:
      - brewing
    volumes:
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./data/influxdb:/var/lib/influxdb
  rethinkdb:
    container_name: auto-home-rethink
    hostname: auto-home-rethink
    image: rethinkdb
    restart: always
    networks:
      - brewing
    volumes:
      #- ./config/rethinkdb.conf:/etc/influxdb/influxdb.conf
      - ./data/rethinkdb:/data
  grafana:
    container_name: auto-home-grafana
    hostname: auto-home-grafana
    image: grafana/grafana
    restart: always
    networks:
      - brewing
    depends_on:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
  autohome:
    container_name: auto-home-server
    hostname: auto-home-server
    image: node:lts-alpine
    restart: always
    depends_on:
      - rethinkdb
      - influxdb
      - grafana
    networks:
      - brewing
    volumes:
      - .:/app
    working_dir: /app
    command: "node ./app.js"
