openapi: 3.0.1
info:
  title: Auto Home
  version: 1.0.0

security:
  - jwt: []
  - api_key: []

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: query
      name: api_key
    jwt:
      type: http
      scheme: bearer
